import React, { createContext, useContext, useState, useEffect, type ReactNode } from 'react';

export type SupportedLanguage = 
  | 'en' // English
  | 'hi' // Hindi (हिन्दी)
  | 'bn' // Bengali (বাংলা)
  | 'mr' // Marathi (मराठी)
  | 'te' // Telugu (తెలుగు)
  | 'ta' // Tamil (தமிழ்)
  | 'gu' // Gujarati (ગુજરાતી)
  | 'ur' // Urdu (اردو)
  | 'kn' // Kannada (ಕನ್ನಡ)
  | 'or' // Odia (ଓଡ଼ିଆ)
  | 'ml'; // Malayalam (മലയാളം)

export interface LanguageInfo {
  code: SupportedLanguage;
  name: string;
  nativeName: string;
  speakers: string;
  region: string;
}

export const TOP_10_INDIAN_LANGUAGES: LanguageInfo[] = [
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', speakers: '528M (43.6%)', region: 'North & Central India' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', speakers: '97M (8.0%)', region: 'West Bengal & East' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', speakers: '83M (6.9%)', region: 'Maharashtra' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు', speakers: '81M (6.7%)', region: 'Andhra Pradesh & Telangana' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', speakers: '69M (5.7%)', region: 'Tamil Nadu & Puducherry' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', speakers: '55M (4.6%)', region: 'Gujarat' },
  { code: 'ur', name: 'Urdu', nativeName: 'اردو', speakers: '51M (4.2%)', region: 'Pan-India' },
  { code: 'kn', name: 'Kannada', nativeName: 'ಕನ್ನಡ', speakers: '44M (3.6%)', region: 'Karnataka' },
  { code: 'or', name: 'Odia', nativeName: 'ଓଡ଼ିଆ', speakers: '38M (3.1%)', region: 'Odisha' },
  { code: 'ml', name: 'Malayalam', nativeName: 'മലയാളം', speakers: '35M (2.9%)', region: 'Kerala & Lakshadweep' },
  { code: 'en', name: 'English', nativeName: 'English', speakers: 'Global', region: 'Pan-India Academic / Corporate' },
];

export const TRANSLATIONS: Record<SupportedLanguage, Record<string, string>> = {
  en: {
    // Brand & Landing
    'capfly': 'CAPFLY',
    'tagline': 'Learn • Connect • Grow',
    'subtitle': 'Bridging Faculty and Industry for a Brighter Future',
    'student_login': 'Student Login',
    'student_sub': 'Explore • Learn • Build Your Future',
    'academia_login': 'Faculty Login',
    'academia_sub': 'Teach • Research • Collaborate',
    'industry_login': 'Industry Login',
    'industry_sub': 'Hire • Mentor • Innovate',
    'institution_login': 'Institution Login',
    'institution_sub': 'Analyze • Track • Empower',
    'languages': 'Languages',
    'select_language': 'Select Language',
    'top_10_languages': 'Top 10 Indian Languages',
    'powered_by': 'Powered by CAPFLY',
    'slogan_connect': 'Connect Collaborate Create Impact',
    'slogan_tomorrow': 'People Skills Opportunities A Brighter Tomorrow',
    'slogan_footer': 'Learn | Connect | Collaborate | Grow',
    'speech_student': 'Learn, Build Skills, Find Opportunities',
    'speech_faculty': 'Teach, Research, Mentor',
    'speech_industry': 'Hire, Collaborate, Innovate',
    'speech_institution': 'Monitor, Analyze, Empower',
    // Portals & Common
    'dashboard': 'Dashboard',
    'overview': 'Overview',
    'logout': 'Logout',
    'notifications': 'Notifications',
    'search': 'Search...',
    'profile': 'Profile',
    'settings': 'Settings',
    'help': 'Help Center',
    'back_to_home': 'Back to Home',
    'confirm_logout': 'Confirm Logout',
    'cancel': 'Cancel',
    'apply': 'Apply Now',
    'enroll': 'Enroll Now',
    'view_details': 'View Details',
    'download_report': 'Download Report',
    'status': 'Status',
    'active': 'Active',
    'completed': 'Completed',
    'pending': 'Pending',
    // Student
    'student_portal': 'Student Portal',
    'opportunities': 'Opportunities',
    'learn_hub': 'Learn Hub',
    'skill_assessments': 'Skills',
    'digital_portfolio': 'Digital Portfolio',
    'daily_goals': 'Daily Goals',
    'leaderboard': 'Leaderboard',
    'resume_readiness': 'Resume Readiness',
    'diagnostic_tests': 'Diagnostic Tests',
    'take_test': 'Take Test',
    // Academia
    'academia_portal': 'Faculty Portal',
    'faculty_engagement': 'Faculty Engagement',
    'student_supervision': 'Student Supervision',
    'upskilling_fdp': 'Upskilling & FDP',
    'research_consultancy': 'Research & Consultancy',
    'naac_reports': 'NAAC Reports',
    'submit_proposal': 'Submit Proposal',
    // Industry
    'industry_portal': 'Industry Portal',
    'talent_matching': 'Talent Matching',
    'job_requisitions': 'Job Requisitions',
    'mentorship_programs': 'Mentorship Programs',
    'college_analytics': 'College Analytics',
    'post_new_job': 'Post Opportunity',
    // Institution
    'institution_portal': 'Institution Portal',
    'students_analytics': 'Student Analytics',
    'faculty_records': 'Faculty Records',
    'industry_collaboration': 'Industry Collaboration',
    'mous_agreements': 'MoUs & Agreements',
    'placement_analysis': 'Placement Analysis',
    'internship_analysis': 'Internship Analysis',
  },
  hi: {
    // Brand & Landing
    'capfly': 'CAPFLY',
    'tagline': 'सीखें • जुड़ें • आगे बढ़ें',
    'subtitle': 'उज्ज्वल भविष्य के लिए शिक्षा और उद्योग को जोड़ना',
    'student_login': 'छात्र लॉगिन',
    'student_sub': 'अन्वेषण करें • सीखें • अपना भविष्य बनाएं',
    'academia_login': 'शिक्षा एवं संकाय लॉगिन',
    'academia_sub': 'सिखाएं • अनुसंधान करें • सहयोग करें',
    'industry_login': 'उद्योग लॉगिन',
    'industry_sub': 'भर्ती करें • मार्गदर्शन दें • नवाचार करें',
    'institution_login': 'संस्थान लॉगिन',
    'institution_sub': 'विश्लेषण करें • ट्रैक करें • सशक्त बनाएं',
    'languages': 'भाषाएं',
    'select_language': 'भाषा चुनें',
    'top_10_languages': 'भारत की शीर्ष 10 प्रमुख भाषाएं',
    'powered_by': 'संचालित द्वारा CAPFLY',
    'slogan_connect': 'जुड़ें सहयोग करें प्रभाव बनाएं',
    'slogan_tomorrow': 'लोग कौशल अवसर एक उज्ज्वल कल',
    'slogan_footer': 'सीखें | जुड़ें | सहयोग करें | आगे बढ़ें',
    'speech_student': 'सीखें, कौशल बनाएं, अवसर खोजें',
    'speech_faculty': 'सिखाएं, अनुसंधान करें, मार्गदर्शन करें',
    'speech_industry': 'भर्ती करें, सहयोग करें, नवाचार करें',
    'speech_institution': 'निगरानी करें, विश्लेषण करें, सशक्त बनाएं',
    // Portals & Common
    'dashboard': 'डैशबोर्ड',
    'overview': 'अवलोकन',
    'logout': 'लॉग आउट',
    'notifications': 'सूचनाएं',
    'search': 'खोजें...',
    'profile': 'प्रोफ़ाइल',
    'settings': 'सेटिंग्स',
    'help': 'सहायता केंद्र',
    'back_to_home': 'मुख्य पृष्ठ पर वापस जाएं',
    'confirm_logout': 'लॉगआउट की पुष्टि करें',
    'cancel': 'रद्द करें',
    'apply': 'आवेदन करें',
    'enroll': 'नामांकन करें',
    'view_details': 'विवरण देखें',
    'download_report': 'रिपोर्ट डाउनलोड करें',
    'status': 'स्थिति',
    'active': 'सक्रिय',
    'completed': 'पूर्ण',
    'pending': 'लंबित',
    // Student
    'student_portal': 'छात्र पोर्टल',
    'opportunities': 'अवसर एवं इंटर्नशिप',
    'learn_hub': 'लर्न हब',
    'skill_assessments': 'कौशल मूल्यांकन',
    'digital_portfolio': 'डिजिटल पोर्टफोलियो',
    'daily_goals': 'दैनिक लक्ष्य',
    'leaderboard': 'लीडरबोर्ड',
    'resume_readiness': 'बायोडाटा तैयारी',
    'diagnostic_tests': 'नैदानिक परीक्षण',
    'take_test': 'परीक्षा दें',
    // Academia
    'academia_portal': 'संकाय एवं शिक्षा पोर्टल',
    'faculty_engagement': 'संकाय सहभागिता',
    'student_supervision': 'छात्र मार्गदर्शन',
    'upskilling_fdp': 'कौशल उन्नयन व एफडीपी',
    'research_consultancy': 'अनुसंधान एवं परामर्श',
    'naac_reports': 'नैक मान्यता रिपोर्ट',
    'submit_proposal': 'प्रस्ताव प्रस्तुत करें',
    // Industry
    'industry_portal': 'उद्योग पोर्टल',
    'talent_matching': 'प्रतिभा मिलान',
    'job_requisitions': 'नौकरी रिक्तियां',
    'mentorship_programs': 'मेंटरशिप कार्यक्रम',
    'college_analytics': 'कॉलेज विश्लेषण',
    'post_new_job': 'नया अवसर पोस्ट करें',
    // Institution
    'institution_portal': 'संस्थान प्रबंधन पोर्टल',
    'students_analytics': 'छात्र विश्लेषण',
    'faculty_records': 'संकाय रिकॉर्ड',
    'industry_collaboration': 'उद्योग सहयोग',
    'mous_agreements': 'एमओयू और समझौते',
    'placement_analysis': 'प्लेसमेंट विश्लेषण',
    'internship_analysis': 'इंटर्नशिप विश्लेषण',
  },
  bn: {
    'capfly': 'CAPFLY',
    'tagline': 'শিখুন • যুক্ত হোন • এগিয়ে যান',
    'subtitle': 'উজ্জ্বল ভবিষ্যতের জন্য শিক্ষা ও শিল্পের মেলবন্ধন',
    'student_login': 'শিক্ষার্থী লগইন',
    'student_sub': 'অন্বেষণ করুন • শিখুন • ভবিষ্যৎ গড়ুন',
    'academia_login': 'শিক্ষাবিদ লগইন',
    'academia_sub': 'শেখান • গবেষণা করুন • সহযোগিতা করুন',
    'industry_login': 'শিল্প লগইন',
    'industry_sub': 'নিয়োগ করুন • পরামর্শ দিন • উদ্ভাবন করুন',
    'institution_login': 'প্রতিষ্ঠান লগইন',
    'institution_sub': 'বিশ্লেষণ করুন • ট্র্যাক করুন • ক্ষমতায়ন করুন',
    'languages': 'ভাষা',
    'select_language': 'ভাষা নির্বাচন করুন',
    'top_10_languages': 'ভারতের শীর্ষ ১০টি ভাষা',
    'powered_by': 'CAPFLY দ্বারা চালিত',
    'slogan_connect': 'যুক্ত হোন সহযোগিতা করুন প্রভাব ফেলুন',
    'slogan_tomorrow': 'মানুষ দক্ষতা সুযোগ এক উজ্জ্বল আগামীকাল',
    'slogan_footer': 'শিখুন | যুক্ত হোন | সহযোগিতা করুন | এগিয়ে যান',
    'speech_student': 'শিখুন, দক্ষতা বাড়ান, সুযোগ খুঁজুন',
    'speech_faculty': 'শেখান, গবেষণা করুন, পরামর্শ দিন',
    'speech_industry': 'নিয়োগ করুন, সহযোগিতা করুন, উদ্ভাবন করুন',
    'speech_institution': 'পর্যবেক্ষণ করুন, বিশ্লেষণ করুন, ক্ষমতায়ন করুন',
    'dashboard': 'ড্যাশবোর্ড',
    'overview': 'সংক্ষিপ্ত বিবরণ',
    'logout': 'লগআউট',
    'notifications': 'বিজ্ঞপ্তি',
    'search': 'অনুসন্ধান করুন...',
    'profile': 'প্রোফাইল',
    'settings': 'সেটিংস',
    'help': 'সহায়তা কেন্দ্র',
    'back_to_home': 'হোমে ফিরে যান',
    'confirm_logout': 'লগআউট নিশ্চিত করুন',
    'cancel': 'বাতিল করুন',
    'apply': 'আবেদন করুন',
    'enroll': 'ভর্তি হন',
    'view_details': 'বিস্তারিত দেখুন',
    'download_report': 'রিপোর্ট ডাউনলোড করুন',
    'status': 'স্থিতি',
    'active': 'সক্রিয়',
    'completed': 'সম্পন্ন',
    'pending': 'মুলতুবি',
    'student_portal': 'শিক্ষার্থী পোর্টাল',
    'opportunities': 'সুযোগ ও ইন্টার্নশিপ',
    'learn_hub': 'লার্নিং হাব',
    'skill_assessments': 'দক্ষতা মূল্যায়ন',
    'digital_portfolio': 'ডিজিটাল পোর্টফোলিও',
    'daily_goals': 'দৈনিক লক্ষ্য',
    'leaderboard': 'লিডারবোর্ড',
    'resume_readiness': 'জীবনবৃত্তান্ত প্রস্তুতি',
    'diagnostic_tests': 'ডায়াগনস্টিক পরীক্ষা',
    'take_test': 'পরীক্ষা দিন',
    'academia_portal': 'একাডেমিয়া পোর্টাল',
    'faculty_engagement': 'অনুষদ ব্যস্ততা',
    'student_supervision': 'শিক্ষার্থী তত্ত্বাবধান',
    'upskilling_fdp': 'দক্ষতা বৃদ্ধি ও এফডিপি',
    'research_consultancy': 'গবেষণা ও পরামর্শ',
    'naac_reports': 'ন্যাক রিপোর্ট',
    'submit_proposal': 'প্রস্তাব জমা দিন',
    'industry_portal': 'শিল্প পোর্টাল',
    'talent_matching': 'মেধা মেলবন্ধন',
    'job_requisitions': 'চাকরির আবেদন',
    'mentorship_programs': 'মেন্টরশিপ প্রোগ্রাম',
    'college_analytics': 'কলেজ বিশ্লেষণ',
    'post_new_job': 'নতুন সুযোগ পোস্ট করুন',
    'institution_portal': 'প্রতিষ্ঠান পোর্টাল',
    'students_analytics': 'শিক্ষার্থী বিশ্লেষণ',
    'faculty_records': 'শিক্ষক রেকর্ড',
    'industry_collaboration': 'শিল্প সহযোগিতা',
    'mous_agreements': 'মউ ও চুক্তি',
    'placement_analysis': 'প্লেসমেন্ট বিশ্লেষণ',
    'internship_analysis': 'ইন্টার্নশিপ বিশ্লেষণ',
  },
  mr: {
    'capfly': 'CAPFLY',
    'tagline': 'शिका • जोडा • प्रगती करा',
    'subtitle': 'उज्ज्वल भविष्यासाठी शिक्षण आणि उद्योग जोडणे',
    'student_login': 'विद्यार्थी लॉगिन',
    'student_sub': 'एक्सप्लोर करा • शिका • भविष्य घडवा',
    'academia_login': 'शैक्षणिक लॉगिन',
    'academia_sub': 'शिकवा • संशोधन करा • सहकार्य करा',
    'industry_login': 'उद्योग लॉगिन',
    'industry_sub': 'भरती करा • मार्गदर्शन करा • नवोपक्रम करा',
    'institution_login': 'संस्था लॉगिन',
    'institution_sub': 'विश्लेषण करा • ट्रॅक करा • सक्षम करा',
    'languages': 'भाषा',
    'select_language': 'भाषा निवडा',
    'top_10_languages': 'भारतातील शीर्ष १० प्रमुख भाषा',
    'powered_by': 'CAPFLY द्वारे समर्थित',
    'slogan_connect': 'जोडा सहकार्य करा प्रभाव पाडा',
    'slogan_tomorrow': 'लोक कौशल्ये संधी एक उज्ज्वल उद्या',
    'slogan_footer': 'शिका | जोडा | सहकार्य करा | प्रगती करा',
    'speech_student': 'शिका, कौशल्ये मिळवा, संधी शोधा',
    'speech_faculty': 'शिकवा, संशोधन करा, मार्गदर्शन करा',
    'speech_industry': 'भरती करा, सहकार्य करा, नवोपक्रम करा',
    'speech_institution': 'निरीक्षण करा, विश्लेषण करा, सक्षम करा',
    'dashboard': 'डॅशबोर्ड',
    'overview': 'आढावा',
    'logout': 'लॉग आउट',
    'notifications': 'सूचना',
    'search': 'शोधा...',
    'profile': 'प्रोफाइल',
    'settings': 'सेटिंग्ज',
    'help': 'मदत केंद्र',
    'back_to_home': 'मुख्य पानावर परत जा',
    'confirm_logout': 'लॉगआउटची पुष्टी करा',
    'cancel': 'रद्द करा',
    'apply': 'अर्ज करा',
    'enroll': 'नोंदणी करा',
    'view_details': 'तपशील पहा',
    'download_report': 'अहवाल डाउनलोड करा',
    'status': 'स्थिती',
    'active': 'सक्रिय',
    'completed': 'पूर्ण',
    'pending': 'प्रलंबित',
    'student_portal': 'विद्यार्थी पोर्टल',
    'opportunities': 'संधी आणि इंटर्नशिप',
    'learn_hub': 'लर्निंग हब',
    'skill_assessments': 'कौशल्य मूल्यांकन',
    'digital_portfolio': 'डिजिटल पोर्टफोलिओ',
    'daily_goals': 'दैनिक उद्दिष्टे',
    'leaderboard': 'लीडरबोर्ड',
    'resume_readiness': 'रेझ्युमे तयारी',
    'diagnostic_tests': 'निदान चाचण्या',
    'take_test': 'चाचणी द्या',
    'academia_portal': 'अकादमी पोर्टल',
    'faculty_engagement': 'प्राध्यापक सहभाग',
    'student_supervision': 'विद्यार्थी मार्गदर्शन',
    'upskilling_fdp': 'कौशल्य विकास आणि एफडीपी',
    'research_consultancy': 'संशोधन आणि सल्लागार',
    'naac_reports': 'नॅक अहवाल',
    'submit_proposal': 'प्रस्ताव सादर करा',
    'industry_portal': 'उद्योग पोर्टल',
    'talent_matching': 'प्रतिभा मॅचिंग',
    'job_requisitions': 'नोकरीच्या मागण्या',
    'mentorship_programs': 'मार्गदर्शन कार्यक्रम',
    'college_analytics': 'महाविद्यालय विश्लेषण',
    'post_new_job': 'संधी पोस्ट करा',
    'institution_portal': 'संस्था पोर्टल',
    'students_analytics': 'विद्यार्थी विश्लेषण',
    'faculty_records': 'प्राध्यापक नोंदी',
    'industry_collaboration': 'उद्योग सहकार्य',
    'mous_agreements': 'सामंजस्य करार',
    'placement_analysis': 'प्लेसमेंट विश्लेषण',
    'internship_analysis': 'इंटर्नशिप विश्लेषण',
  },
  te: {
    'capfly': 'CAPFLY',
    'tagline': 'నేర్చుకోండి • కనెక్ట్ అవ్వండి • ఎదగండి',
    'subtitle': 'ఉజ్వల భవిష్యత్తు కోసం విద్య మరియు పరిశ్రమల అనుసంధానం',
    'student_login': 'విద్యార్థి లాగిన్',
    'student_sub': 'అన్వేషించండి • నేర్చుకోండి • భవిష్యత్తు నిర్మించుకోండి',
    'academia_login': 'అధ్యాపకుల లాగిన్',
    'academia_sub': 'బోధించండి • పరిశోధించండి • సహకరించండి',
    'industry_login': 'పరిశ్రమ లాగిన్',
    'industry_sub': 'నియమించండి • మార్గదర్శనం చేయండి • ఆవిష్కరించండి',
    'institution_login': 'సంస్థ లాగిన్',
    'institution_sub': 'విశ్లేషించండి • ట్రాక్ చేయండి • సాధికారత కల్పించండి',
    'languages': 'భాషలు',
    'select_language': 'భాషను ఎంచుకోండి',
    'top_10_languages': 'భారతదేశంలో అగ్ర 10 భాషలు',
    'powered_by': 'CAPFLY ద్వారా అందించబడుతోంది',
    'slogan_connect': 'కనెక్ట్ అవ్వండి సహకరించండి ప్రభావం చూపండి',
    'slogan_tomorrow': 'ప్రజలు నైపుణ్యాలు అవకాశాలు ఉజ్వల రేపటి కోసం',
    'slogan_footer': 'నేర్చుకోండి | కనెక్ట్ అవ్వండి | సహకరించండి | ఎదగండి',
    'speech_student': 'నేర్చుకోండి, నైపుణ్యాలు పెంచుకోండి, అవకాశాలు పొందండి',
    'speech_faculty': 'బోధించండి, పరిశోధించండి, మార్గదర్శకత్వం చేయండి',
    'speech_industry': 'ఉద్యోగాలు ఇవ్వండి, సహకరించండి, ఆవిష్కరించండి',
    'speech_institution': 'పర్యవేక్షించండి, విశ్లేషించండి, బలోపేతం చేయండి',
    'dashboard': 'డ్యాష్‌బోర్డ్',
    'overview': 'అవలోకనం',
    'logout': 'లాగౌట్',
    'notifications': 'నోటిఫికేషన్లు',
    'search': 'శోధించండి...',
    'profile': 'ప్రొఫైల్',
    'settings': 'సెట్టింగ్‌లు',
    'help': 'సహాయ కేంద్రం',
    'back_to_home': 'హోమ్‌కు తిరిగి వెళ్ళు',
    'confirm_logout': 'లాగౌట్‌ను నిర్ధారించండి',
    'cancel': 'రద్దు చేయండి',
    'apply': 'దరఖాస్తు చేసుకోండి',
    'enroll': 'చేరండి',
    'view_details': 'వివరాలు చూడండి',
    'download_report': 'నివేదిక డౌన్‌లోడ్ చేయండి',
    'status': 'స్థితి',
    'active': 'క్రియాశీలక',
    'completed': 'పూర్తయింది',
    'pending': 'వేచి ఉంది',
    'student_portal': 'విద్యార్థి పోర్టల్',
    'opportunities': 'అవకాశాలు & ఇంటర్న్‌షిప్‌లు',
    'learn_hub': 'లెర్నింగ్ హబ్',
    'skill_assessments': 'నైపుణ్య అంచనా',
    'digital_portfolio': 'డిజిటల్ పోర్ట్‌ఫోలియో',
    'daily_goals': 'రోజువారీ లక్ష్యాలు',
    'leaderboard': 'లీడర్‌బోర్డ్',
    'resume_readiness': 'రెజ్యూమ్ సంసిద్ధత',
    'diagnostic_tests': 'డయాగ్నస్టిక్ పరీక్షలు',
    'take_test': 'పరీక్ష రాయండి',
    'academia_portal': 'అకాడెమియా పోర్టల్',
    'faculty_engagement': 'అధ్యాపకుల భాగస్వామ్యం',
    'student_supervision': 'విద్యార్థుల పర్యవేక్షణ',
    'upskilling_fdp': 'నైపుణ్యాభివృద్ధి & ఎఫ్‌డిపి',
    'research_consultancy': 'పరిశోధన & కన్సల్టెన్సీ',
    'naac_reports': 'న్యాక్ నివేదికలు',
    'submit_proposal': 'ప్రతిపాదనను సమర్పించండి',
    'industry_portal': 'పరిశ్రమ పోర్టల్',
    'talent_matching': 'ప్రతిభ సరిపోలిక',
    'job_requisitions': 'ఉద్యోగ అవకాశాలు',
    'mentorship_programs': 'మెంటార్‌షిప్ ప్రోగ్రామ్‌లు',
    'college_analytics': 'కళాశాల విశ్లేషణలు',
    'post_new_job': 'కొత్త అవకాశాన్ని పోస్ట్ చేయండి',
    'institution_portal': 'సంస్థ పోర్టల్',
    'students_analytics': 'విద్యార్థుల విశ్లేషణ',
    'faculty_records': 'అధ్యాపకుల రికార్డులు',
    'industry_collaboration': 'పరిశ్రమల సహకారం',
    'mous_agreements': 'ఒప్పందాలు & ఎంఓయూలు',
    'placement_analysis': 'ప్లేస్‌మెంట్ విశ్లేషణ',
    'internship_analysis': 'ఇంటర్న్‌షిప్ విశ్లేషణ',
  },
  ta: {
    'capfly': 'CAPFLY',
    'tagline': 'கற்றுக்கொள்ளுங்கள் • இணையுங்கள் • வளருங்கள்',
    'subtitle': 'பிரகாசமான எதிர்காலத்திற்காக கல்வியையும் தொழிற்துறையையும் இணைத்தல்',
    'student_login': 'மாணவர் உள்நுழைவு',
    'student_sub': 'ஆராயுங்கள் • கற்றுக்கொள்ளுங்கள் • எதிர்காலத்தை உருவாக்குங்கள்',
    'academia_login': 'கல்வியாளர் உள்நுழைவு',
    'academia_sub': 'கற்பியுங்கள் • ஆராய்ச்சி செய்யுங்கள் • ஒத்துழையுங்கள்',
    'industry_login': 'தொழில் துறை உள்நுழைவு',
    'industry_sub': 'பணியமர்த்துங்கள் • வழிகாட்டுங்கள் • புதுமை படைத்திடுங்கள்',
    'institution_login': 'கல்வி நிறுவனம் உள்நுழைவு',
    'institution_sub': 'பகுப்பாய்வு செய்யுங்கள் • கண்காணிக்கவும் • அதிகாரம் பெறுங்கள்',
    'languages': 'மொழிகள்',
    'select_language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    'top_10_languages': 'இந்தியாவின் முதல் 10 முக்கிய மொழிகள்',
    'powered_by': 'வழங்குவது CAPFLY',
    'slogan_connect': 'இணையுங்கள் ஒத்துழையுங்கள் தாக்கத்தை ஏற்படுத்துங்கள்',
    'slogan_tomorrow': 'மனிதர்கள் திறன்கள் வாய்ப்புகள் ஒரு ஒளிமயமான எதிர்காலம்',
    'slogan_footer': 'கற்றுக்கொள்ளுங்கள் | இணையுங்கள் | ஒத்துழையுங்கள் | வளருங்கள்',
    'speech_student': 'கற்க, திறன்களை வளர்க்க, வாய்ப்புகளை பெற',
    'speech_faculty': 'கற்பிக்க, ஆராய்ச்சி செய்ய, வழிகாட்ட',
    'speech_industry': 'பணியமர்த்த, ஒத்துழைக்க, புதுமை படைக்க',
    'speech_institution': 'கண்காணிக்க, பகுப்பாய்வு செய்ய, மேம்படுத்த',
    'dashboard': 'டாஷ்போர்டு',
    'overview': 'கண்ணோட்டம்',
    'logout': 'வெளியேறு',
    'notifications': 'அறிவிப்புகள்',
    'search': 'தேடுக...',
    'profile': 'சுயவிவரம்',
    'settings': 'அமைப்புகள்',
    'help': 'உதவி மையம்',
    'back_to_home': 'முகப்புக்குத் திரும்பு',
    'confirm_logout': 'வெளியேறுவதை உறுதிப்படுத்தவும்',
    'cancel': 'ரத்து செய்',
    'apply': 'விண்ணப்பிக்கவும்',
    'enroll': 'பதிவு செய்யவும்',
    'view_details': 'விவரங்களை காண்க',
    'download_report': 'அறிக்கையை பதிவிறக்கவும்',
    'status': 'நிலை',
    'active': 'செயலில் உள்ளது',
    'completed': 'முடிந்தது',
    'pending': 'நிலுவையில் உள்ளது',
    'student_portal': 'மாணவர் தளம்',
    'opportunities': 'வாய்ப்புகள் & இன்டர்ன்ஷிப்',
    'learn_hub': 'கற்றல் மையம்',
    'skill_assessments': 'திறன் மதிப்பீடுகள்',
    'digital_portfolio': 'டிஜிட்டல் போர்ட்ஃபோலியோ',
    'daily_goals': 'தினசரி இலக்குகள்',
    'leaderboard': 'முன்னிலை பலகை',
    'resume_readiness': 'ரெஸ்யூம் தயார்நிலை',
    'diagnostic_tests': 'கண்டறியும் சோதனைகள்',
    'take_test': 'தேர்வு எழுதுங்கள்',
    'academia_portal': 'கல்வியாளர் தளம்',
    'faculty_engagement': 'ஆசிரியர் ஈடுபாடு',
    'student_supervision': 'மாணவர் மேற்பார்வை',
    'upskilling_fdp': 'திறன் மேம்பாடு & எஃப்டிபி',
    'research_consultancy': 'ஆராய்ச்சி & ஆலோசனை',
    'naac_reports': 'நாக் அறிக்கைகள்',
    'submit_proposal': 'முன்மொழிவை சமர்ப்பிக்கவும்',
    'industry_portal': 'தொழில்துறை தளம்',
    'talent_matching': 'திறமை பொருத்தம்',
    'job_requisitions': 'வேலை தேவைகள்',
    'mentorship_programs': 'வழிகாட்டல் திட்டங்கள்',
    'college_analytics': 'கல்லூரி பகுப்பாய்வு',
    'post_new_job': 'புதிய வாய்ப்பை வெளியிடு',
    'institution_portal': 'நிறுவன தளம்',
    'students_analytics': 'மாணவர் பகுப்பாய்வு',
    'faculty_records': 'ஆசிரியர் பதிவுகள்',
    'industry_collaboration': 'தொழில்துறை ஒத்துழைப்பு',
    'mous_agreements': 'புரிந்துணர்வு ஒப்பந்தங்கள்',
    'placement_analysis': 'வேலைவாய்ப்பு பகுப்பாய்வு',
    'internship_analysis': 'பயிற்சி பகுப்பாய்வு',
  },
  gu: {
    'capfly': 'CAPFLY',
    'tagline': 'શીખો • જોડાઓ • આગળ વધો',
    'subtitle': 'ઉજ્જવળ ભવિષ્ય માટે શિક્ષણ અને ઉદ્યોગને જોડવું',
    'student_login': 'વિદ્યાર્થી લૉગિન',
    'student_sub': 'અન્વેષણ કરો • શીખો • ભવિષ્ય બનાવો',
    'academia_login': 'શિક્ષણવિદ્ લૉગિન',
    'academia_sub': 'શીખવો • સંશોધન કરો • સહયોગ કરો',
    'industry_login': 'ઉદ્યોગ લૉગિન',
    'industry_sub': 'ભરતી કરો • માર્ગદર્શન આપો • નવીનતા લાવો',
    'institution_login': 'સંસ્થા લૉગિન',
    'institution_sub': 'વિશ્લેષણ કરો • ટ્રેક કરો • સશક્ત બનાવો',
    'languages': 'ભાષાઓ',
    'select_language': 'ભાષા પસંદ કરો',
    'top_10_languages': 'ભારતની ટોચની ૧૦ મુખ્ય ભાષાઓ',
    'powered_by': 'સંચાલિત CAPFLY',
    'slogan_connect': 'જોડાઓ સહયોગ કરો પ્રભાવ પાડો',
    'slogan_tomorrow': 'લોકો કુશળતા તકો એક ઉજ્જવળ આવતીકાલ',
    'slogan_footer': 'શીખો | જોડાઓ | સહયોગ કરો | આગળ વધો',
    'speech_student': 'શીખો, કૌશલ્ય બનાવો, તકો મેળવો',
    'speech_faculty': 'શીખવો, સંશોધન કરો, માર્ગદર્શન આપો',
    'speech_industry': 'ભરતી કરો, સહયોગ કરો, નવીનતા લાવો',
    'speech_institution': 'નિરીક્ષણ કરો, વિશ્લેષણ કરો, સશક્ત બનાવો',
    'dashboard': 'ડેશબોર્ડ',
    'overview': 'વિહંગાવલોકન',
    'logout': 'લૉગ આઉટ',
    'notifications': 'સૂચનાઓ',
    'search': 'શોધો...',
    'profile': 'પ્રોફાઇલ',
    'settings': 'સેટિંગ્સ',
    'help': 'સહાય કેન્દ્ર',
    'back_to_home': 'હોમ પેજ પર પાછા જાઓ',
    'confirm_logout': 'લૉગઆઉટની પુષ્ટિ કરો',
    'cancel': 'રદ કરો',
    'apply': 'અરજી કરો',
    'enroll': 'નોંધણી કરો',
    'view_details': 'વિગતો જુઓ',
    'download_report': 'અહેવાલ ડાઉનલોડ કરો',
    'status': 'સ્થિતિ',
    'active': 'સક્રિય',
    'completed': 'પૂર્ણ',
    'pending': 'બાકી',
    'student_portal': 'વિદ્યાર્થી પોર્ટલ',
    'opportunities': 'તકો અને ઇન્ટર્નશીપ',
    'learn_hub': 'લર્ન હબ',
    'skill_assessments': 'કૌશલ્ય મૂલ્યાંકન',
    'digital_portfolio': 'ડિજિટલ પોર્ટફોલિયો',
    'daily_goals': 'દૈનિક લક્ષ્યો',
    'leaderboard': 'લીડરબોર્ડ',
    'resume_readiness': 'રિઝ્યુમ તૈયારી',
    'diagnostic_tests': 'નિદાન પરીક્ષણો',
    'take_test': 'પરીક્ષા આપો',
    'academia_portal': 'શિક્ષણવિદ્ પોર્ટલ',
    'faculty_engagement': 'ફેકલ્ટી જોડાણ',
    'student_supervision': 'વિદ્યાર્થી માર્ગદર્શન',
    'upskilling_fdp': 'કૌશલ્ય વૃદ્ધિ અને એફડીપી',
    'research_consultancy': 'સંશોધન અને કન્સલ્ટન્સી',
    'naac_reports': 'નેક અહેવાલો',
    'submit_proposal': 'દરખાસ્ત સબમિટ કરો',
    'industry_portal': 'ઉદ્યોગ પોર્ટલ',
    'talent_matching': 'ટેલેન્ટ મેચિંગ',
    'job_requisitions': 'નોકરીની માંગ',
    'mentorship_programs': 'મેન્ટરશીપ પ્રોગ્રામ',
    'college_analytics': 'કોલેજ એનાલિટિક્સ',
    'post_new_job': 'નવી તક પોસ્ટ કરો',
    'institution_portal': 'સંસ્થા પોર્ટલ',
    'students_analytics': 'વિદ્યાર્થી વિશ્લેષણ',
    'faculty_records': 'ફેકલ્ટી રેકોર્ડ્સ',
    'industry_collaboration': 'ઉદ્યોગ સહયોગ',
    'mous_agreements': 'સમજૂતી કરારો',
    'placement_analysis': 'પ્લેસમેન્ટ વિશ્લેષણ',
    'internship_analysis': 'ઇન્ટર્નશીપ વિશ્લેષણ',
  },
  ur: {
    'capfly': 'CAPFLY',
    'tagline': 'سیکھیں • جڑیں • آگے بڑھیں',
    'subtitle': 'روشن مستقبل کے لیے تعلیم اور صنعت کو جوڑنا',
    'student_login': 'طالب علم لاگ ان',
    'student_sub': 'دریافت کریں • سیکھیں • اپنا مستقبل بنائیں',
    'academia_login': 'اساتذہ لاگ ان',
    'academia_sub': 'پڑھائیں • تحقیق کریں • تعاون کریں',
    'industry_login': 'صنعت لاگ ان',
    'industry_sub': 'ملازمت دیں • رہنمائی کریں • جدت لائیں',
    'institution_login': 'ادارہ لاگ ان',
    'institution_sub': 'تجزیہ کریں • نگرانی کریں • بااختیار بنائیں',
    'languages': 'زبانیں',
    'select_language': 'زبان منتخب کریں',
    'top_10_languages': 'ہندوستان کی سرفہرست 10 زبانیں',
    'powered_by': 'کی طرف سے طاقتور CAPFLY',
    'slogan_connect': 'جڑیں تعاون کریں اثر ڈالیں',
    'slogan_tomorrow': 'لوگ ہنر مواقع ایک روشن کل',
    'slogan_footer': 'سیکھیں | جڑیں | تعاون کریں | آگے بڑھیں',
    'speech_student': 'سیکھیں، ہنر بنائیں، مواقع تلاش کریں',
    'speech_faculty': 'پڑھائیں، تحقیق کریں، رہنمائی کریں',
    'speech_industry': 'ملازمت دیں، تعاون کریں، نئی راہیں نکالیں',
    'speech_institution': 'نگرانی کریں، تجزیہ کریں، بااختیار بنائیں',
    'dashboard': 'ڈیش بورڈ',
    'overview': 'جائزہ',
    'logout': 'لاگ آؤٹ',
    'notifications': 'اطلاعات',
    'search': 'تلاش کریں...',
    'profile': 'پروفائل',
    'settings': 'ترتیبات',
    'help': 'مدد کا مرکز',
    'back_to_home': 'ہوم پر واپس جائیں',
    'confirm_logout': 'لاگ آؤٹ کی تصدیق کریں',
    'cancel': 'منسوخ کریں',
    'apply': 'درخواست دیں',
    'enroll': 'داخلہ لیں',
    'view_details': 'تفصیلات دیکھیں',
    'download_report': 'رپورٹ ڈاؤن لوڈ کریں',
    'status': 'حیثیت',
    'active': 'فعال',
    'completed': 'مکمل',
    'pending': 'زیر التواء',
    'student_portal': 'طالب علم پورٹل',
    'opportunities': 'مواقع اور انٹرن شپ',
    'learn_hub': 'لرن ہب',
    'skill_assessments': 'مہارت کا جائزہ',
    'digital_portfolio': 'ڈیجیٹل پورٹ فولیو',
    'daily_goals': 'روزانہ کے اہداف',
    'leaderboard': 'لیڈر بورڈ',
    'resume_readiness': 'ریزیومے کی تیاری',
    'diagnostic_tests': 'تشخیصی ٹیسٹ',
    'take_test': 'ٹیسٹ دیں',
    'academia_portal': 'اکیڈمیا پورٹل',
    'faculty_engagement': 'اساتذہ کی سرگرمیاں',
    'student_supervision': 'طلباء کی رہنمائی',
    'upskilling_fdp': 'مہارت کی ترقی اور ایف ڈی پی',
    'research_consultancy': 'تحقیق اور مشاورت',
    'naac_reports': 'نیک رپورٹس',
    'submit_proposal': 'تجویز پیش کریں',
    'industry_portal': 'صنعتی پورٹل',
    'talent_matching': 'ٹیلنٹ میچنگ',
    'job_requisitions': 'ملازمت کی ضرورت',
    'mentorship_programs': 'رہنمائی کے پروگرام',
    'college_analytics': 'کالج تجزیات',
    'post_new_job': 'نیا موقع پوسٹ کریں',
    'institution_portal': 'ادارہ جاتی پورٹل',
    'students_analytics': 'طلباء کے تجزیات',
    'faculty_records': 'اساتذہ کے ریکارڈ',
    'industry_collaboration': 'صنعتی تعاون',
    'mous_agreements': 'معاہدے اور ایم او یو',
    'placement_analysis': 'پلیسمنٹ تجزیہ',
    'internship_analysis': 'انٹرن شپ تجزیہ',
  },
  kn: {
    'capfly': 'CAPFLY',
    'tagline': 'ಕಲಿಯಿರಿ • ಸಂಪರ್ಕಿಸಿ • ಬೆಳೆಯಿರಿ',
    'subtitle': 'ಉಜ್ವಲ ಭವಿಷ್ಯಕ್ಕಾಗಿ ಶಿಕ್ಷಣ ಮತ್ತು ಉದ್ಯಮವನ್ನು ಬೆಸೆಯುವುದು',
    'student_login': 'ವಿದ್ಯಾರ್ಥಿ ಲಾಗಿನ್',
    'student_sub': 'ಅನ್ವೇಷಿಸಿ • ಕಲಿಯಿರಿ • ನಿಮ್ಮ ಭವಿಷ್ಯವನ್ನು ನಿರ್ಮಿಸಿ',
    'academia_login': 'ಅಕಾಡೆಮಿಕ್ ಲಾಗಿನ್',
    'academia_sub': 'ಬೋಧಿಸಿ • ಸಂಶೋಧಿಸಿ • ಸಹಕರಿಸಿ',
    'industry_login': 'ಉದ್ಯಮ ಲಾಗಿನ್',
    'industry_sub': 'ನೇಮಕ ಮಾಡಿ • ಮಾರ್ಗದರ್ಶನ ನೀಡಿ • ನಾವೀನ್ಯತೆ ಬೆಳೆಸಿ',
    'institution_login': 'ಸಂಸ್ಥೆ ಲಾಗಿನ್',
    'institution_sub': 'ವಿಶ್ಲೇಷಿಸಿ • ಟ್ರ್ಯಾಕ್ ಮಾಡಿ • ಸಬಲೀಕರಣಗೊಳಿಸಿ',
    'languages': 'ಭಾಷೆಗಳು',
    'select_language': 'ಭಾಷೆಯನ್ನು ಆರಿಸಿ',
    'top_10_languages': 'ಭಾರತದ ಪ್ರಮುಖ 10 ಭಾಷೆಗಳು',
    'powered_by': 'CAPFLY ನಿಂದ ನಡೆಸಲ್ಪಡುತ್ತಿದೆ',
    'slogan_connect': 'ಸಂಪರ್ಕಿಸಿ ಸಹಕರಿಸಿ ಪರಿಣಾಮ ಬೀರಿ',
    'slogan_tomorrow': 'ಜನರು ಕೌಶಲ್ಯಗಳು ಅವಕಾಶಗಳು ಉಜ್ವಲ ನಾಳೆ',
    'slogan_footer': 'ಕಲಿಯಿರಿ | ಸಂಪರ್ಕಿಸಿ | ಸಹಕರಿಸಿ | ಬೆಳೆಯಿರಿ',
    'speech_student': 'ಕಲಿಯಿರಿ, ಕೌಶಲ್ಯ ಬೆಳೆಸಿಕೊಳ್ಳಿ, ಅವಕಾಶಗಳನ್ನು ಪಡೆಯಿರಿ',
    'speech_faculty': 'ಬೋಧಿಸಿ, ಸಂಶೋಧನೆ ನಡೆಸಿ, ಮಾರ್ಗದರ್ಶನ ನೀಡಿ',
    'speech_industry': 'ನೇಮಕ ಮಾಡಿ, ಸಹಕರಿಸಿ, ಹೊಸತನ ತನ್ನಿ',
    'speech_institution': 'ಮೇಲ್ವಿಚಾರಣೆ ನಡೆಸಿ, ವಿಶ್ಲೇಷಿಸಿ, ಸಶಕ್ತಗೊಳಿಸಿ',
    'dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'overview': 'ಅವಲೋಕನ',
    'logout': 'ಲಾಗ್‌ಔಟ್',
    'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
    'search': 'ಹುಡುಕಿ...',
    'profile': 'ಪ್ರೊಫೈಲ್',
    'settings': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'help': 'ಸಹಾಯ ಕೇಂದ್ರ',
    'back_to_home': 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',
    'confirm_logout': 'ಲಾಗ್‌ಔಟ್ ದೃಢೀಕರಿಸಿ',
    'cancel': 'ರದ್ದುಮಾಡಿ',
    'apply': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
    'enroll': 'ದಾಖಲಾಗಿ',
    'view_details': 'ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'download_report': 'ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ',
    'status': 'ಸ್ಥಿತಿ',
    'active': 'ಸಕ್ರಿಯ',
    'completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'pending': 'ಬಾಕಿ ಉಳಿದಿದೆ',
    'student_portal': 'ವಿದ್ಯಾರ್ಥಿ ಪೋರ್ಟಲ್',
    'opportunities': 'ಅವಕಾಶಗಳು & ಇಂಟರ್ನ್‌ಶಿಪ್‌ಗಳು',
    'learn_hub': 'ಕಲಿಕಾ ಹಬ್',
    'skill_assessments': 'ಕೌಶಲ್ಯ ಮೌಲ್ಯಮಾಪನ',
    'digital_portfolio': 'ಡಿಜಿಟಲ್ ಪೋರ್ಟ್‌ಫೋಲಿಯೊ',
    'daily_goals': 'ದೈನಂದಿನ ಗುರಿಗಳು',
    'leaderboard': 'ಲೀಡರ್‌ಬೋರ್ಡ್',
    'resume_readiness': 'ರೆಸ್ಯೂಮ್ ಸಿದ್ಧತೆ',
    'diagnostic_tests': 'ಡಯಾಗ್ನೋಸ್ಟಿಕ್ ಪರೀಕ್ಷೆಗಳು',
    'take_test': 'ಪರೀಕ್ಷೆ ತೆಗೆದುಕೊಳ್ಳಿ',
    'academia_portal': 'ಅಕಾಡೆಮಿ ಪೋರ್ಟಲ್',
    'faculty_engagement': 'ಅಧ್ಯಾಪಕರ ತೊಡಗಿಸಿಕೊಳ್ಳುವಿಕೆ',
    'student_supervision': 'ವಿದ್ಯಾರ್ಥಿ ಮೇಲ್ವಿಚಾರಣೆ',
    'upskilling_fdp': 'ಕೌಶಲ್ಯ ವೃದ್ಧಿ & ಎಫ್‌ಡಿಪಿ',
    'research_consultancy': 'ಸಂಶೋಧನೆ & ಸಲಹಾ ಸೇವೆ',
    'naac_reports': 'ನ್ಯಾಕ್ ವರದಿಗಳು',
    'submit_proposal': 'ಪ್ರಸ್ತಾವನೆ ಸಲ್ಲಿಸಿ',
    'industry_portal': 'ಉದ್ಯಮ ಪೋರ್ಟಲ್',
    'talent_matching': 'ಪ್ರತಿಭಾ ಹೊಂದಾಣಿಕೆ',
    'job_requisitions': 'ಉದ್ಯೋಗಾವಕಾಶಗಳು',
    'mentorship_programs': 'ಮಾರ್ಗದರ್ಶನ ಕಾರ್ಯಕ್ರಮಗಳು',
    'college_analytics': 'ಕಾಲೇಜು ವಿಶ್ಲೇಷಣೆ',
    'post_new_job': 'ಹೊಸ ಅವಕಾಶ ಪೋಸ್ಟ್ ಮಾಡಿ',
    'institution_portal': 'ಸಂಸ್ಥೆ ಪೋರ್ಟಲ್',
    'students_analytics': 'ವಿದ್ಯಾರ್ಥಿ ವಿಶ್ಲೇಷಣೆ',
    'faculty_records': 'ಅಧ್ಯಾಪಕರ ದಾಖಲೆಗಳು',
    'industry_collaboration': 'ಉದ್ಯಮ ಸಹಯೋಗ',
    'mous_agreements': 'ಒಪ್ಪಂದಗಳು & ಒಡಂಬಡಿಕೆಗಳು',
    'placement_analysis': 'ಪ್ಲೇಸ್‌ಮೆಂಟ್ ವಿಶ್ಲೇಷಣೆ',
    'internship_analysis': 'ಇಂಟರ್ನ್‌ಶಿಪ್ ವಿಶ್ಲೇಷಣೆ',
  },
  or: {
    'capfly': 'CAPFLY',
    'tagline': 'ଶିଖନ୍ତୁ • ଯୋଡ଼ି ହୁଅନ୍ତୁ • ଆଗକୁ ବଢ଼ନ୍ତୁ',
    'subtitle': 'ଉଜ୍ଜ୍ୱଳ ଭବିଷ୍ୟତ ପାଇଁ ଶିକ୍ଷା ଏବଂ ଶିଳ୍ପର ସଂଯୋଗ',
    'student_login': 'ଛାତ୍ର ଲଗଇନ୍',
    'student_sub': 'ଅନୁସନ୍ଧାନ କରନ୍ତୁ • ଶିଖନ୍ତୁ • ଭବିଷ୍ୟତ ଗଢ଼ନ୍ତୁ',
    'academia_login': 'ଶିକ୍ଷାବିତ୍ ଲଗଇନ୍',
    'academia_sub': 'ଶିକ୍ଷା ଦିଅନ୍ତୁ • ଗବେଷଣା କରନ୍ତୁ • ସହଯୋଗ କରନ୍ତୁ',
    'industry_login': 'ଶିଳ୍ପ ଲଗଇନ୍',
    'industry_sub': 'ନିଯୁକ୍ତି ଦିଅନ୍ତୁ • ମାର୍ଗଦର୍ଶନ କରନ୍ତୁ • ନୂତନତା ଆଣନ୍ତୁ',
    'institution_login': 'ଅନୁଷ୍ଠାନ ଲଗଇନ୍',
    'institution_sub': 'ବିଶ୍ଳେଷଣ କରନ୍ତୁ • ଟ୍ରାକ୍ କରନ୍ତୁ • ସଶକ୍ତ କରନ୍ତୁ',
    'languages': 'ଭାଷା',
    'select_language': 'ଭାଷା ବାଛନ୍ତୁ',
    'top_10_languages': 'ଭାରତର ପ୍ରମୁଖ ୧୦ଟି ଭାଷା',
    'powered_by': 'CAPFLY ଦ୍ୱାରା ପରିଚାଳିତ',
    'slogan_connect': 'ସଂଯୋଗ କରନ୍ତୁ ସହଯୋଗ କରନ୍ତୁ ପ୍ରଭାବ ସୃଷ୍ଟି କରନ୍ତୁ',
    'slogan_tomorrow': 'ଲୋକମାନେ ଦକ୍ଷତା ସୁଯୋଗ ଏକ ଉଜ୍ଜ୍ୱଳ ଆଗାମୀ କାଲି',
    'slogan_footer': 'ଶିଖନ୍ତୁ | ସଂଯୋଗ କରନ୍ତୁ | ସହଯୋଗ କରନ୍ତୁ | ବଢ଼ନ୍ତୁ',
    'speech_student': 'ଶିଖନ୍ତୁ, ଦକ୍ଷତା ବିକାଶ କରନ୍ତୁ, ସୁଯୋଗ ଖୋଜନ୍ତୁ',
    'speech_faculty': 'ଶିକ୍ଷାଦାନ କରନ୍ତୁ, ଗବେଷଣା କରନ୍ତୁ, ମାର୍ଗଦର୍ଶନ କରନ୍ତୁ',
    'speech_industry': 'ନିଯୁକ୍ତି ଦିଅନ୍ତୁ, ସହଯୋଗ କରନ୍ତୁ, ନୂତନତା ଆଣନ୍ତୁ',
    'speech_institution': 'ନିରୀକ୍ଷଣ କରନ୍ତୁ, ବିଶ୍ଳେଷଣ କରନ୍ତୁ, ସଶକ୍ତ କରନ୍ତୁ',
    'dashboard': 'ଡ୍ୟାସବୋର୍ଡ',
    'overview': 'ସମୀକ୍ଷା',
    'logout': 'ଲଗଆଉଟ୍',
    'notifications': 'ବିଜ୍ଞପ୍ତି',
    'search': 'ସନ୍ଧାନ କରନ୍ତୁ...',
    'profile': 'ପ୍ରୋଫାଇଲ୍',
    'settings': 'ସେଟିଙ୍ଗ୍ସ',
    'help': 'ସହାୟତା କେନ୍ଦ୍ର',
    'back_to_home': 'ମୂଳ ପୃଷ୍ଠାକୁ ଫେରନ୍ତୁ',
    'confirm_logout': 'ଲଗଆଉଟ୍ ନିଶ୍ଚିତ କରନ୍ତୁ',
    'cancel': 'ବାତିଲ୍ କରନ୍ତୁ',
    'apply': 'ଆବେଦନ କରନ୍ତୁ',
    'enroll': 'ନାମ ଲେଖାନ୍ତୁ',
    'view_details': 'ବିବରଣୀ ଦେଖନ୍ତୁ',
    'download_report': 'ରିପୋର୍ଟ ଡାଉନଲୋଡ୍ କରନ୍ତୁ',
    'status': 'ସ୍ଥିତି',
    'active': 'ସକ୍ରିୟ',
    'completed': 'ସମ୍ପୂର୍ଣ୍ଣ',
    'pending': 'ବକେୟା',
    'student_portal': 'ଛାତ୍ର ପୋର୍ଟାଲ',
    'opportunities': 'ସୁଯୋଗ ଏବଂ ଇଣ୍ଟର୍ନସିପ୍',
    'learn_hub': 'ଲର୍ଣ୍ଣିଂ ହବ୍',
    'skill_assessments': 'ଦକ୍ଷତା ମୂଲ୍ୟାଙ୍କନ',
    'digital_portfolio': 'ଡିଜିଟାଲ୍ ପୋର୍ଟଫୋଲିଓ',
    'daily_goals': 'ଦୈନିକ ଲକ୍ଷ୍ୟ',
    'leaderboard': 'ଲିଡରବୋର୍ଡ',
    'resume_readiness': 'ରେଜ୍ୟୁମେ ପ୍ରସ୍ତୁତି',
    'diagnostic_tests': 'ପରୀକ୍ଷଣ',
    'take_test': 'ପରୀକ୍ଷା ଦିଅନ୍ତୁ',
    'academia_portal': 'ଶିକ୍ଷା ପୋର୍ଟାଲ',
    'faculty_engagement': 'ଅଧ୍ୟାପକ ସମ୍ପୃକ୍ତି',
    'student_supervision': 'ଛାତ୍ର ତତ୍ତ୍ୱାବଧାନ',
    'upskilling_fdp': 'ଦକ୍ଷତା ବୃଦ୍ଧି ଏବଂ ଏଫଡିପି',
    'research_consultancy': 'ଗବେଷଣା ଏବଂ ପରାମର୍ଶ',
    'naac_reports': 'ନାକ୍ ରିପୋର୍ଟ',
    'submit_proposal': 'ପ୍ରସ୍ତାବ ଦାଖଲ କରନ୍ତୁ',
    'industry_portal': 'ଶିଳ୍ପ ପୋର୍ଟାଲ',
    'talent_matching': 'ପ୍ରତିଭା ମେଳକ',
    'job_requisitions': 'ଚାକିରି ଆବଶ୍ୟକତା',
    'mentorship_programs': 'ମାର୍ଗଦର୍ଶନ କାର୍ଯ୍ୟକ୍ରମ',
    'college_analytics': 'କଲେଜ ବିଶ୍ଳେଷଣ',
    'post_new_job': 'ନୂତନ ସୁଯୋଗ ପୋଷ୍ଟ କରନ୍ତୁ',
    'institution_portal': 'ଅନୁଷ୍ଠାନ ପୋର୍ଟାଲ',
    'students_analytics': 'ଛାତ୍ର ବିଶ୍ଳେଷଣ',
    'faculty_records': 'ଅଧ୍ୟାପକ ରେକର୍ଡ',
    'industry_collaboration': 'ଶିଳ୍ପ ସହଯୋଗ',
    'mous_agreements': 'ଚୁକ୍ତିନାମା ଏବଂ ଏମଓୟୁ',
    'placement_analysis': 'ନିଯୁକ୍ତି ବିଶ୍ଳେଷଣ',
    'internship_analysis': 'ଇଣ୍ଟର୍ନସିପ୍ ବିଶ୍ଳେଷଣ',
  },
  ml: {
    'capfly': 'CAPFLY',
    'tagline': 'പഠിക്കുക • ബന്ധപ്പെടുക • വളരുക',
    'subtitle': 'ശോഭനമായ ഭാവിക്കായി വിദ്യാഭ്യാസവും വ്യവസായവും തമ്മിൽ ബന്ധിപ്പിക്കുന്നു',
    'student_login': 'വിദ്യാർത്ഥി ലോഗിൻ',
    'student_sub': 'പര്യവേക്ഷണം ചെയ്യുക • പഠിക്കുക • ഭാവി കെട്ടിപ്പടുക്കുക',
    'academia_login': 'അക്കാദമിക് ലോഗിൻ',
    'academia_sub': 'പഠിപ്പിക്കുക • ഗവേഷണം ചെയ്യുക • സഹകരിക്കുക',
    'industry_login': 'വ്യവസായ ലോഗിൻ',
    'industry_sub': 'നിയമിക്കുക • വഴികാട്ടുക • നവീകരിക്കുക',
    'institution_login': 'സ്ഥാപന ലോഗിൻ',
    'institution_sub': 'വിശകലനം ചെയ്യുക • ട്രാക്ക് ചെയ്യുക • ശാക്തീകരിക്കുക',
    'languages': 'ഭാഷകൾ',
    'select_language': 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    'top_10_languages': 'ഇന്ത്യയിലെ പ്രധാന 10 ഭാഷകൾ',
    'powered_by': 'CAPFLY നൽകുന്നത്',
    'slogan_connect': 'ബന്ധപ്പെടുക സഹകരിക്കുക സ്വാധീനം ചെലുത്തുക',
    'slogan_tomorrow': 'ആളുകൾ കഴിവുകൾ അവസരങ്ങൾ ഒരു ശോഭനമായ നാളെ',
    'slogan_footer': 'പഠിക്കുക | ബന്ധപ്പെടുക | സഹകരിക്കുക | വളരുക',
    'speech_student': 'പഠിക്കുക, കഴിവുകൾ വളർത്തുക, അവസരങ്ങൾ കണ്ടെത്തുക',
    'speech_faculty': 'പഠിപ്പിക്കുക, ഗവേഷണം നടത്തുക, മാർഗ്ഗനിർദ്ദേശം നൽകുക',
    'speech_industry': 'നിയമിക്കുക, സഹകരിക്കുക, പുതിയ മുന്നേറ്റങ്ങൾ നടത്തുക',
    'speech_institution': 'മേൽനോട്ടം വഹിക്കുക, വിശകലനം ചെയ്യുക, ശാക്തീകരിക്കുക',
    'dashboard': 'ഡാഷ്‌ബോർഡ്',
    'overview': 'അവലോകനം',
    'logout': 'ലോഗ്ഔട്ട്',
    'notifications': 'അറിയിപ്പുകൾ',
    'search': 'തിരയുക...',
    'profile': 'പ്രൊഫൈൽ',
    'settings': 'ക്രമീകരണങ്ങൾ',
    'help': 'സഹായ കേന്ദ്രം',
    'back_to_home': 'ഹോമിലേക്ക് മടങ്ങുക',
    'confirm_logout': 'ലോഗ്ഔട്ട് സ്ഥിരീകരിക്കുക',
    'cancel': 'റദ്ദാക്കുക',
    'apply': 'അപേക്ഷിക്കുക',
    'enroll': 'ചേരുക',
    'view_details': 'വിശദാംശങ്ങൾ കാണുക',
    'download_report': 'റിപ്പോർട്ട് ഡൗൺലോഡ് ചെയ്യുക',
    'status': 'നില',
    'active': 'സജീവം',
    'completed': 'പൂർത്തിയായി',
    'pending': 'തീർച്ചപ്പെടുത്തിയിട്ടില്ല',
    'student_portal': 'വിദ്യാർത്ഥി പോർട്ടൽ',
    'opportunities': 'അവസരങ്ങളും ഇന്റേൺഷിപ്പുകളും',
    'learn_hub': 'ലേൺ ഹബ്ബ്',
    'skill_assessments': 'നൈപുണ്യ വിലയിരുത്തലുകൾ',
    'digital_portfolio': 'ഡിജിറ്റൽ പോർട്ട്ഫോളിയോ',
    'daily_goals': 'പ്രതിദിന ലക്ഷ്യങ്ങൾ',
    'leaderboard': 'ലീഡർബോർഡ്',
    'resume_readiness': 'റെസ്യൂമെ സന്നദ്ധത',
    'diagnostic_tests': 'ഡയഗ്നോസ്റ്റിക് ടെസ്റ്റുകൾ',
    'take_test': 'ടെസ്റ്റ് എഴുതുക',
    'academia_portal': 'അക്കാദമിയ പോർട്ടൽ',
    'faculty_engagement': 'അധ്യാപക ഇടപെടൽ',
    'student_supervision': 'വിദ്യാർത്ഥി മേൽനോട്ടം',
    'upskilling_fdp': 'നൈപുണ്യ വികസനവും എഫ്ഡിപിയും',
    'research_consultancy': 'ഗവേഷണവും കൺസൾട്ടൻസിയും',
    'naac_reports': 'നാക് റിപ്പോർട്ടുകൾ',
    'submit_proposal': 'നിർദ്ദേശം സമർപ്പിക്കുക',
    'industry_portal': 'വ്യവസായ പോർട്ടൽ',
    'talent_matching': 'പ്രതിഭ പൊരുത്തപ്പെടുത്തൽ',
    'job_requisitions': 'തൊഴിൽ ആവശ്യകതകൾ',
    'mentorship_programs': 'മെന്റർഷിപ്പ് പ്രോഗ്രാമുകൾ',
    'college_analytics': 'കോളേജ് വിശകലനം',
    'post_new_job': 'പുതിയ അവസരം പോസ്റ്റ് ചെയ്യുക',
    'institution_portal': 'സ്ഥാപന പോർട്ടൽ',
    'students_analytics': 'വിദ്യാർത്ഥി വിശകലനം',
    'faculty_records': 'അധ്യാപക രേഖകൾ',
    'industry_collaboration': 'വ്യവസായ സഹകരണം',
    'mous_agreements': 'ധാരണാപത്രങ്ങളും കരാറുകളും',
    'placement_analysis': 'പ്ലേസ്‌മെന്റ് വിശകലനം',
    'internship_analysis': 'ഇന്റേൺഷിപ്പ് വിശകലനം',
  }
};

interface LanguageContextType {
  currentLanguage: SupportedLanguage;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string, fallback?: string) => string;
  languages: LanguageInfo[];
  currentLangInfo: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [currentLanguage, setCurrentLanguageState] = useState<SupportedLanguage>(() => {
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('capfly_selected_language');
      if (saved && (saved in TRANSLATIONS)) {
        return saved as SupportedLanguage;
      }
    }
    return 'en';
  });

  const setLanguage = (lang: SupportedLanguage) => {
    setCurrentLanguageState(lang);
    if (typeof window !== 'undefined') {
      localStorage.setItem('capfly_selected_language', lang);
      document.documentElement.lang = lang;
      if (lang === 'ur') {
        document.documentElement.dir = 'rtl';
      } else {
        document.documentElement.dir = 'ltr';
      }

      // Trigger Google Translate engine for full DOM multilingual translation
      try {
        if (lang === 'en') {
          // Clear Google Translate cookie
          document.cookie = 'googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;';
          document.cookie = 'googtrans=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/; domain=' + window.location.hostname;
        } else {
          // Set Google Translate cookie
          document.cookie = `googtrans=/en/${lang}; path=/;`;
          document.cookie = `googtrans=/en/${lang}; path=/; domain=${window.location.hostname};`;
        }

        // If Google Translate select box is present, trigger it
        const select = document.querySelector<HTMLSelectElement>('.goog-te-combo');
        if (select) {
          select.value = lang;
          select.dispatchEvent(new Event('change'));
        }
      } catch (e) {
        console.warn('Multilingual dispatcher notice:', e);
      }
    }
  };

  useEffect(() => {
    // Inject Google Translate script dynamically if not already present
    if (typeof window !== 'undefined') {
      document.documentElement.lang = currentLanguage;
      if (currentLanguage === 'ur') {
        document.documentElement.dir = 'rtl';
      } else {
        document.documentElement.dir = 'ltr';
      }

      if (!document.getElementById('google-translate-script')) {
        const script = document.createElement('script');
        script.id = 'google-translate-script';
        script.type = 'text/javascript';
        script.src = '//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';
        script.async = true;
        document.body.appendChild(script);

        (window as any).googleTranslateElementInit = () => {
          try {
            new (window as any).google.translate.TranslateElement({
              pageLanguage: 'en',
              includedLanguages: 'hi,bn,mr,te,ta,gu,ur,kn,or,ml,en',
              autoDisplay: false,
            }, 'google_translate_element');
          } catch (err) {
            // translation container ready
          }
        };
      }
    }
  }, [currentLanguage]);

  const t = (key: string, fallback?: string): string => {
    const langDict = TRANSLATIONS[currentLanguage] || TRANSLATIONS.en;
    if (langDict[key]) {
      return langDict[key];
    }
    const fallbackDict = TRANSLATIONS.en;
    if (fallbackDict[key]) {
      return fallbackDict[key];
    }
    return fallback || key;
  };

  const currentLangInfo = TOP_10_INDIAN_LANGUAGES.find(l => l.code === currentLanguage) || TOP_10_INDIAN_LANGUAGES[0];

  return (
    <LanguageContext.Provider
      value={{
        currentLanguage,
        setLanguage,
        t,
        languages: TOP_10_INDIAN_LANGUAGES,
        currentLangInfo,
      }}
    >
      <div id="google_translate_element" style={{ display: 'none' }} />
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
